### ISSUE TITLE
Invalid unit: flex

### ISSUE THREAD

**Issue by josueayala27** [natemoo-re/satori-html#4] opened 2022-10-14 22:12 UTC
Hey, I'm just trying to create a vue wrapper and I got the following errors on console:

```
Error: Invalid unit: flex
    at Mu (index.js?ce72:1:1)
    at new Gr (index.js?ce72:1:1)
    at new Fe (index.js?ce72:1:1)
    at Ge (utils.ts?27ad:68:1)
    at lr (expand.ts?0aa2:297:1)
    at en (index.ts?4543:30:1)
    at gt (layout.ts?bda2:98:1)
    at gt.next (<anonymous>)
    at vu (satori.ts?dc42:98:1)
    at VueComponent.initSatori (App.vue?11c4:33:1)

utils.ts?27ad:103 Error: Invalid unit: column
    at Mu (index.js?ce72:1:1)
    at new Gr (index.js?ce72:1:1)
    at new Fe (index.js?ce72:1:1)
    at Ge (utils.ts?27ad:68:1)
    at lr (expand.ts?0aa2:297:1)
    at en (index.ts?4543:31:1)
    at gt (layout.ts?bda2:98:1)
    at gt.next (<anonymous>)
    at vu (satori.ts?dc42:98:1)
    at VueComponent.initSatori (App.vue?11c4:33:1)
```

This is my method call:

```jsx
    async initSatori() {
      const font = await fetch("http://localhost:8080/Inter-Regular.ttf");
      const buffer = await font.arrayBuffer();

      const markup = html`<div>hello, world</div>`;
      const svg = await satori(markup, {
        width: 600,
        height: 400,
        fonts: [
          {
            name: "Inter",
            data: buffer,
            weight: 400,
            style: "normal",
          },
        ],
      });

      this.svg = svg;
    },
```

At least I'm receiving the svg generated 👨🏻‍💻, worse I don't understand why these errors are generated in the console.

**Comment by natemoo-re** [comment] 2022-10-17 13:02
This seems very much like an upstream issue with `satori` itself, but it's hard to know without a full reproduction. Mind sharing a full repro?

**Comment by natemoo-re** [comment] 2022-12-12 14:57
Closing this since I can't repro. Feel free to reopen with more details if you can provide a reproduction!

**Closed by natemoo-re** 2022-12-12 14:57 UTC
